### ISSUE TITLE
Processo travando na inicialização

### ISSUE THREAD

**Issue by tiagotsukahara** [brunogasparetto/fluig-docker-dev#1]
Estou com um problema na inicialização do fluig, fica travado, estou rodando o docker em um Mac M1 com 2 CPU e 4GB Ram.
Passou por algo parecido?

**Comment by brunogasparetto** [comment]
@tiagotsukahara , talvez seja falta de memória. A documentação do Fluig pede pelo menos 16 GB de RAM, isso sem considerar que está rodando em docker. Além de uma quantidade razoável de processador. E ainda tem o consumo do banco de dados e mailhog.

Talvez configurando o Fluig pra um dimensionamento menor, seguindo essa [documentação do Fluig](https://tdn.totvs.com/display/public/fluig/Modelo+de+dimensionamento) possa ajudar. 

Mas pra muita coisa de aprendizado também dá pra usar o https://lab.fluig.com/ . Claro que aí precisa de um cuidado extra pra não publicar senhas/credenciais por lá.
